### ISSUE TITLE
maxStale Will never works

### ISSUE THREAD

**Issue by Huzhengtao** [llfbandit/dio_cache_interceptor#77] opened 2022-05-27 20:15 UTC
I set maxStale = Duration(seconds: 1)，but response always from cache ...
```
      response = await _dio.get(url,
          options: _cacheOption
              .copyWith(
                  policy: CachePolicy.forceCache,
                  maxStale: Nullable(Duration(seconds: 1)))   // for test
              .toOptions()
            ..headers = headers
            ..responseType = ResponseType.plain);
      print(response.extra);
```

seems the problem is &&
```
      if ((maxStale == null || maxStale == const Duration(microseconds: 0)) &&
          response.isStaled()) {
        await cacheStore.delete(cacheKey);
        return null;
      }
```

**Comment by llfbandit** [comment] 2022-05-28 07:07
Duplicate of #78

**Closed by llfbandit** 2022-05-28 07:07 UTC

**Comment by Huzhengtao** [comment] 2022-05-28 07:23
no,It's different.When set both of maxstale and forcecache, the cache will always be hit regardless of the Duration value, and the cache will not be deleted forever

**Comment by llfbandit** [comment] 2022-05-28 07:28
Yes this is expected and documented.
```dart
/// Overrides any HTTP directive to delete entry past this duration.
  ///
  /// Giving this value to a later request will update the previously
  /// cached response with this directive.
  ///
  /// This allows to postpone the deletion.
  final Duration? maxStale;
```
